#!/bin/sh
#shellcheck disable=SC2015

die() {
    printf "\033[0;31m${@}\033[0m\n"
    exit 1
}

repo="$(/bin/git rev-parse --show-toplevel 2>/dev/null)"
if test "$?" -ne 0; then
    die "You must run this script from the work tree of a git repository"
fi

[ $# -ne 1 ] && echo "Usage: pusht <commit_msg>" && exit 1 ||
    {
        n_tag=$(new_tag)
        echo "New tag: ${n_tag}"
        read -r -p "Are you sure? [Y/n] " response
        if [ "$response" = "y" ] || [ "$response" = "Y" ]; then
            git commit -m "$1"
            git tag -a "${n_tag}" -m "$1"
            git push --follow-tags
        fi
    }
